"""Initial migration.

Revision ID: 22425d132bec
Revises: 3b772cfcb493
Create Date: 2024-08-06 21:08:37.412404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22425d132bec'
down_revision = '3b772cfcb493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.alter_column('sponsor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.alter_column('sponsor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
