"""Initial migration.

Revision ID: 3e82af550f1b
Revises: 
Create Date: 2024-08-10 23:09:05.949527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e82af550f1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag', sa.Boolean(), nullable=True))

    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.drop_column('flag')

    with op.batch_alter_table('influencer', schema=None) as batch_op:
        batch_op.drop_column('flag')

    # ### end Alembic commands ###
