"""Initial migration.

Revision ID: 8399dbb0e661
Revises: 3e82af550f1b
Create Date: 2024-08-11 19:04:44.083491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8399dbb0e661'
down_revision = '3e82af550f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adrequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.drop_column('accepted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adrequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
